### ISSUE TITLE
Restructure courses to follow Ontario high school curriculum

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/physics-in-motion#140]
#### Task

Using the Ontario Curriculum for Grades 11 and 12, restructure the Courses page to follow a similar structure.

#### Acceptance Criteria

- [x] Rename "Classical Mechanics" course to something like "High School Physics"
- [x] Hide "Mathematics" and "Resources" course temporarily
- [x] Reorganize and rename lesson modules to follow a similar structure as the Ontario Curriculum for Grades 11 and 12
