### ISSUE TITLE
Refactor Motion in two-dimensions lesson module

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/physics-in-motion#142]
#### Task

Refactor the Motion in two-dimensions lesson module to follow an average high school curriculum.

#### Acceptance Criteria

- [x] Cover topics on displacement and velocity
- [x] Cover topics on acceleration
- [x] Cover topics on projectile motion
