### ISSUE TITLE
Refactor Forces and the Laws of Motion lesson module

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/physics-in-motion#143]
#### Task

Refactor the Forces and the Laws of Motion lesson module to follow an average high school curriculum.

#### Acceptance Criteria

- [x] Cover topics on Newton's First Law of Motion
- [x] Cover topics on Newton's Second Law of Motion
- [x] Cover topics on Newton's Third Law of Motion
