### ISSUE TITLE
Refactor existing lesson modules to fit new lesson module structure

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/physics-in-motion#144]
#### Task

Refactor existing lesson modules to fit new lesson module structure.

#### Acceptance Criteria

- [x] Motion in One Dimension
- [x] Motion in Two Dimensions
- [x] Forces and the Laws of Motion
- [x] Circular Motion
- [x] Work and Energy
- [x] Linear Momentum and Collisions
- [x] Rotational Motion and Angular Momentum
- [x] Oscillations
- [x] Waves and Sounds
- [x] Electricity and Magnetism
- [x] Fluid Mechanics

**Comment by LeNPaul** [comment]
Just refactor previous lesson modules to follow the new lessons module structure.
